services:
  postgres-db:
    image: postgres:17
    container_name: quizopia_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: quizopia_db
      POSTGRES_USER: hhtuann
      POSTGRES_PASSWORD: 216556

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - quizopia_network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quiz_user -d quizopia_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7.2-alpine
    container_name: quizopia_redis
    restart: unless-stopped

    command: redis-server --requirepass redis_password

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - quizopia_network

volumes:
  postgres_data:
  redis_data:

networks:
  quizopia_network:
    driver: bridge
