-- ====================================================================
-- Quizopia MVP Core Schema
-- PostgreSQL 15+
-- Scope: 32 tables
-- Standalone reference. Split into Flyway migrations in the application.
-- ====================================================================

BEGIN;

-- [Identity & Authorization] Tài khoản và danh tính đăng nhập.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    full_name VARCHAR(150) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(20) NOT NULL DEFAULT 'OTHER',
    avatar_url VARCHAR(500),
    phone_ciphertext BYTEA,
    phone_iv BYTEA,
    phone_key_version INTEGER,
    phone_lookup_hmac VARCHAR(128),
    identification_ciphertext BYTEA,
    identification_iv BYTEA,
    identification_key_version INTEGER,
    identification_lookup_hmac VARCHAR(128),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    CONSTRAINT ck_users_1 CHECK (gender IN ('MALE','FEMALE','OTHER')),
    CONSTRAINT ck_users_2 CHECK (status IN ('PENDING','ACTIVE','LOCKED','DISABLED','ARCHIVED'))
);
CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_phone_lookup_hmac ON users (phone_lookup_hmac);

-- [Identity & Authorization] Danh mục vai trò hệ thống.
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    system_role BOOLEAN NOT NULL DEFAULT TRUE
);

-- [Identity & Authorization] Danh mục mã quyền ổn định.
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    module VARCHAR(80) NOT NULL
);

-- [Identity & Authorization] Gán nhiều vai trò cho một user.
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_by BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id) ON DELETE SET NULL
);

-- [Identity & Authorization] Gán quyền vào vai trò.
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

-- [Identity & Authorization] Refresh token opaque, rotation và reuse detection.
CREATE TABLE refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    token_family_id UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    replaced_by_session_id BIGINT,
    ip_address INET,
    user_agent VARCHAR(500),
    last_used_at TIMESTAMPTZ,
    CONSTRAINT fk_refresh_sessions_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_sessions_replaced_by_session_id FOREIGN KEY (replaced_by_session_id) REFERENCES refresh_sessions (id) ON DELETE SET NULL
);
CREATE INDEX idx_refresh_sessions_user_id ON refresh_sessions (user_id);
CREATE INDEX idx_refresh_sessions_family_id ON refresh_sessions (token_family_id);
CREATE INDEX idx_refresh_sessions_expires_at ON refresh_sessions (expires_at);

-- [Academic] Trường học.
CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

-- [Academic] Khối lớp 10/11/12.
CREATE TABLE grade_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    school_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_grade_level_school_code UNIQUE (school_id, code),
    CONSTRAINT fk_grade_levels_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT
);
CREATE INDEX idx_grade_levels_school_id ON grade_levels (school_id);

-- [Academic] Môn học theo trường và khối lớp, bám sát nghiệp vụ tham chiếu.
CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    school_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    grade_level_id BIGINT NOT NULL,
    CONSTRAINT uk_subjects_school_grade_code UNIQUE (school_id, grade_level_id, code),
    CONSTRAINT fk_subjects_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT,
    CONSTRAINT fk_subjects_grade_level_id FOREIGN KEY (grade_level_id) REFERENCES grade_levels (id) ON DELETE RESTRICT
);
CREATE INDEX idx_subjects_school_id ON subjects (school_id);
CREATE INDEX idx_subjects_grade_level_id ON subjects (grade_level_id);

-- [Academic] Hồ sơ giáo viên, composition với users.
CREATE TABLE teacher_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    school_id BIGINT NOT NULL,
    teacher_code VARCHAR(50) NOT NULL,
    title VARCHAR(100),
    employment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_teacher_school_code UNIQUE (school_id, teacher_code),
    CONSTRAINT fk_teacher_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_teacher_profiles_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT
);
CREATE INDEX idx_teacher_profiles_school_id ON teacher_profiles (school_id);

-- [Academic] Hồ sơ nghiệp vụ học sinh; MVP yêu cầu có tài khoản users.
CREATE TABLE student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    school_id BIGINT NOT NULL,
    student_code VARCHAR(50) NOT NULL,
    enrollment_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_student_school_code UNIQUE (school_id, student_code),
    CONSTRAINT fk_student_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_profiles_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT
);
CREATE INDEX idx_student_profiles_school_id ON student_profiles (school_id);

-- [Academic] Lớp học cụ thể; MVP lưu trực tiếp school, grade, academic_year và homeroom teacher.
CREATE TABLE classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    school_id BIGINT NOT NULL,
    grade_level_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    homeroom_teacher_id BIGINT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    academic_year VARCHAR(9) NOT NULL,
    CONSTRAINT uk_classrooms_school_year_name UNIQUE (school_id, academic_year, name),
    CONSTRAINT ck_classrooms_1 CHECK (academic_year ~ '^[0-9]{4}-[0-9]{4}$'),
    CONSTRAINT ck_classrooms_2 CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    CONSTRAINT fk_classrooms_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT,
    CONSTRAINT fk_classrooms_grade_level_id FOREIGN KEY (grade_level_id) REFERENCES grade_levels (id) ON DELETE RESTRICT,
    CONSTRAINT fk_classrooms_homeroom_teacher_id FOREIGN KEY (homeroom_teacher_id) REFERENCES teacher_profiles (id) ON DELETE SET NULL
);
CREATE INDEX idx_classrooms_grade_level_id ON classrooms (grade_level_id);
CREATE INDEX idx_classrooms_homeroom_teacher_id ON classrooms (homeroom_teacher_id);

-- [Academic] Học sinh trong lớp, thay student_class.
CREATE TABLE classroom_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    identification_number VARCHAR(50),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    joined_at DATE,
    left_at DATE,
    confirmed_at TIMESTAMPTZ,
    CONSTRAINT uk_classroom_student UNIQUE (classroom_id, student_profile_id),
    CONSTRAINT uk_classroom_identification UNIQUE (classroom_id, identification_number),
    CONSTRAINT fk_classroom_memberships_classroom_id FOREIGN KEY (classroom_id) REFERENCES classrooms (id) ON DELETE RESTRICT,
    CONSTRAINT fk_classroom_memberships_student_profile_id FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE RESTRICT
);
CREATE INDEX idx_classroom_memberships_student_id ON classroom_memberships (student_profile_id);

-- [Academic] Giáo viên dạy nhiều môn.
CREATE TABLE teacher_subjects (
    teacher_profile_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_teacher_subjects PRIMARY KEY (teacher_profile_id, subject_id),
    CONSTRAINT fk_teacher_subjects_teacher_profile_id FOREIGN KEY (teacher_profile_id) REFERENCES teacher_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_teacher_subjects_subject_id FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);

-- [Question Bank] Ngân hàng câu hỏi thuộc một môn và do giáo viên sở hữu.
CREATE TABLE question_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    owner_teacher_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    visibility VARCHAR(30) NOT NULL DEFAULT 'PRIVATE',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_question_banks_owner_name UNIQUE (owner_teacher_id, name),
    CONSTRAINT fk_question_banks_subject_id FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE RESTRICT,
    CONSTRAINT fk_question_banks_owner_teacher_id FOREIGN KEY (owner_teacher_id) REFERENCES teacher_profiles (id) ON DELETE RESTRICT
);
CREATE INDEX idx_question_banks_subject_id ON question_banks (subject_id);

-- [Question Bank] Danh tính ổn định của câu hỏi.
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    question_bank_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    current_version_number INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    CONSTRAINT uk_question_bank_code UNIQUE (question_bank_id, code),
    CONSTRAINT fk_questions_question_bank_id FOREIGN KEY (question_bank_id) REFERENCES question_banks (id) ON DELETE RESTRICT,
    CONSTRAINT fk_questions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX idx_questions_bank_id ON questions (question_bank_id);

-- [Question Bank] Phiên bản nội dung câu hỏi.
CREATE TABLE question_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    question_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    question_type VARCHAR(40) NOT NULL,
    content TEXT NOT NULL,
    explanation TEXT,
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    default_score NUMERIC(10,2) NOT NULL DEFAULT 1,
    answer_key JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by BIGINT NOT NULL,
    CONSTRAINT uk_question_version UNIQUE (question_id, version_number),
    CONSTRAINT ck_question_versions_1 CHECK (version_number > 0),
    CONSTRAINT ck_question_versions_2 CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','ESSAY')),
    CONSTRAINT ck_question_versions_3 CHECK (difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT ck_question_versions_4 CHECK (default_score >= 0),
    CONSTRAINT fk_question_versions_question_id FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_question_versions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX idx_question_versions_question_id ON question_versions (question_id);

-- [Question Bank] Lựa chọn của câu hỏi.
CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    question_version_id BIGINT NOT NULL,
    option_key VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    position INTEGER NOT NULL,
    CONSTRAINT uk_question_option_key UNIQUE (question_version_id, option_key),
    CONSTRAINT uk_question_option_position UNIQUE (question_version_id, position),
    CONSTRAINT fk_question_options_question_version_id FOREIGN KEY (question_version_id) REFERENCES question_versions (id) ON DELETE CASCADE
);
CREATE INDEX idx_question_options_version_id ON question_options (question_version_id);

-- [Exam] Mục đích kỳ thi.
CREATE TABLE exam_purposes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    school_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(150) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    semester_hint INTEGER,
    CONSTRAINT uk_exam_purpose_school_code UNIQUE (school_id, code),
    CONSTRAINT fk_exam_purposes_school_id FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT
);

-- [Exam] Danh tính đề thi; nội dung nằm trong exam_versions.
CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    owner_teacher_id BIGINT NOT NULL,
    purpose_id BIGINT,
    code VARCHAR(80) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    exam_type VARCHAR(30) NOT NULL DEFAULT 'TEST',
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    current_version_number INTEGER NOT NULL DEFAULT 1,
    subject_id BIGINT NOT NULL,
    CONSTRAINT uk_exams_subject_code UNIQUE (subject_id, code),
    CONSTRAINT fk_exams_owner_teacher_id FOREIGN KEY (owner_teacher_id) REFERENCES teacher_profiles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exams_purpose_id FOREIGN KEY (purpose_id) REFERENCES exam_purposes (id) ON DELETE SET NULL,
    CONSTRAINT fk_exams_subject_id FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE RESTRICT
);
CREATE INDEX idx_exams_subject_id ON exams (subject_id);
CREATE INDEX idx_exams_owner_teacher_id ON exams (owner_teacher_id);

-- [Exam] Phiên bản/snapshot đề.
CREATE TABLE exam_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    instructions TEXT,
    header TEXT,
    total_points NUMERIC(10,2) NOT NULL DEFAULT 0,
    default_duration_minutes INTEGER NOT NULL DEFAULT 0,
    randomize_questions BOOLEAN NOT NULL DEFAULT FALSE,
    randomize_options BOOLEAN NOT NULL DEFAULT FALSE,
    hide_section_titles BOOLEAN NOT NULL DEFAULT FALSE,
    reset_numbering_per_section BOOLEAN NOT NULL DEFAULT FALSE,
    show_result_policy VARCHAR(30) NOT NULL DEFAULT 'NO',
    show_answer_policy VARCHAR(30) NOT NULL DEFAULT 'NO',
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    published_at TIMESTAMPTZ,
    CONSTRAINT uk_exam_version UNIQUE (exam_id, version_number),
    CONSTRAINT fk_exam_versions_exam_id FOREIGN KEY (exam_id) REFERENCES exams (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_versions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX idx_exam_versions_exam_id ON exam_versions (exam_id);

-- [Exam] Phần câu hỏi.
CREATE TABLE exam_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_version_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    instructions TEXT,
    position INTEGER NOT NULL,
    CONSTRAINT uk_exam_section_position UNIQUE (exam_version_id, position),
    CONSTRAINT fk_exam_sections_exam_version_id FOREIGN KEY (exam_version_id) REFERENCES exam_versions (id) ON DELETE CASCADE
);
CREATE INDEX idx_exam_sections_version_id ON exam_sections (exam_version_id);

-- [Exam] Snapshot câu hỏi trong đề.
CREATE TABLE exam_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_version_id BIGINT NOT NULL,
    exam_section_id BIGINT,
    source_question_id BIGINT,
    source_question_version_id BIGINT,
    question_code VARCHAR(80) NOT NULL,
    question_type VARCHAR(40) NOT NULL,
    content TEXT NOT NULL,
    explanation TEXT,
    points NUMERIC(10,2) NOT NULL,
    position INTEGER NOT NULL,
    answer_key JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uk_exam_question_position UNIQUE (exam_version_id, position),
    CONSTRAINT ck_exam_questions_1 CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','ESSAY')),
    CONSTRAINT ck_exam_questions_2 CHECK (points >= 0),
    CONSTRAINT ck_exam_questions_3 CHECK (position >= 0),
    CONSTRAINT fk_exam_questions_exam_version_id FOREIGN KEY (exam_version_id) REFERENCES exam_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_questions_exam_section_id FOREIGN KEY (exam_section_id) REFERENCES exam_sections (id) ON DELETE SET NULL,
    CONSTRAINT fk_exam_questions_source_question_id FOREIGN KEY (source_question_id) REFERENCES questions (id) ON DELETE SET NULL,
    CONSTRAINT fk_exam_questions_source_question_version_id FOREIGN KEY (source_question_version_id) REFERENCES question_versions (id) ON DELETE SET NULL
);
CREATE INDEX idx_exam_questions_version_id ON exam_questions (exam_version_id);
CREATE INDEX idx_exam_questions_section_id ON exam_questions (exam_section_id);

-- [Exam] Snapshot lựa chọn trong đề.
CREATE TABLE exam_question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_question_id BIGINT NOT NULL,
    option_key VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    position INTEGER NOT NULL,
    CONSTRAINT uk_exam_question_option_key UNIQUE (exam_question_id, option_key),
    CONSTRAINT uk_exam_question_option_position UNIQUE (exam_question_id, position),
    CONSTRAINT fk_exam_question_options_exam_question_id FOREIGN KEY (exam_question_id) REFERENCES exam_questions (id) ON DELETE CASCADE
);
CREATE INDEX idx_exam_question_options_question_id ON exam_question_options (exam_question_id);

-- [Exam] Ca thi tách khỏi nội dung đề.
CREATE TABLE exam_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_version_id BIGINT NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    close_at TIMESTAMPTZ NOT NULL,
    duration_minutes INTEGER NOT NULL,
    late_entry_minutes INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 1,
    auto_submit BOOLEAN NOT NULL DEFAULT TRUE,
    shuffle_questions BOOLEAN NOT NULL DEFAULT FALSE,
    shuffle_options BOOLEAN NOT NULL DEFAULT FALSE,
    result_release_policy VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    access_code_hash VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    CONSTRAINT ck_exam_sessions_1 CHECK (close_at > start_at),
    CONSTRAINT ck_exam_sessions_2 CHECK (duration_minutes > 0),
    CONSTRAINT ck_exam_sessions_3 CHECK (late_entry_minutes >= 0),
    CONSTRAINT ck_exam_sessions_4 CHECK (max_attempts > 0),
    CONSTRAINT ck_exam_sessions_5 CHECK (result_release_policy IN ('IMMEDIATE','AFTER_SESSION_CLOSE','MANUAL')),
    CONSTRAINT ck_exam_sessions_6 CHECK (status IN ('DRAFT','SCHEDULED','OPEN','CLOSED','CANCELLED','ARCHIVED')),
    CONSTRAINT fk_exam_sessions_exam_version_id FOREIGN KEY (exam_version_id) REFERENCES exam_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_sessions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX idx_exam_sessions_version_id ON exam_sessions (exam_version_id);
CREATE INDEX idx_exam_sessions_time ON exam_sessions (start_at, close_at);
CREATE INDEX idx_exam_sessions_status ON exam_sessions (status);

-- [Exam] Danh sách học sinh được phép dự ca thi; lớp được mở rộng thành participant rows.
CREATE TABLE exam_session_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_session_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL DEFAULT 'EXPLICIT',
    extra_time_minutes INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'ELIGIBLE',
    CONSTRAINT uk_session_participant UNIQUE (exam_session_id, student_profile_id),
    CONSTRAINT ck_exam_session_participants_1 CHECK (source_type IN ('EXPLICIT','CLASSROOM_EXPANSION')),
    CONSTRAINT ck_exam_session_participants_2 CHECK (extra_time_minutes >= 0),
    CONSTRAINT ck_exam_session_participants_3 CHECK (status IN ('ELIGIBLE','BLOCKED','REMOVED')),
    CONSTRAINT fk_exam_session_participants_exam_session_id FOREIGN KEY (exam_session_id) REFERENCES exam_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_session_participants_student_profile_id FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE RESTRICT
);
CREATE INDEX idx_exam_session_participants_student_id ON exam_session_participants (student_profile_id);

-- [Attempt & Grading] Một lượt làm bài.
CREATE TABLE attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    exam_session_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    started_at TIMESTAMPTZ,
    deadline_at TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ,
    last_saved_at TIMESTAMPTZ,
    client_instance_id UUID,
    submission_idempotency_key VARCHAR(100),
    CONSTRAINT uk_attempt_session_student_number UNIQUE (exam_session_id, student_profile_id, attempt_number),
    CONSTRAINT uk_attempt_submit_key UNIQUE (student_profile_id, submission_idempotency_key),
    CONSTRAINT ck_attempts_1 CHECK (attempt_number > 0),
    CONSTRAINT ck_attempts_2 CHECK (status IN ('CREATED','IN_PROGRESS','SUBMITTED','AUTO_SUBMITTED','GRADED','CANCELLED')),
    CONSTRAINT fk_attempts_exam_session_id FOREIGN KEY (exam_session_id) REFERENCES exam_sessions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_attempts_student_profile_id FOREIGN KEY (student_profile_id) REFERENCES student_profiles (id) ON DELETE RESTRICT
);
CREATE INDEX idx_attempts_session_status ON attempts (exam_session_id, status);
CREATE INDEX idx_attempts_student_id ON attempts (student_profile_id);

-- [Attempt & Grading] Thứ tự câu và lựa chọn ổn định.
CREATE TABLE attempt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    exam_question_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    option_order JSONB,
    CONSTRAINT uk_attempt_question UNIQUE (attempt_id, exam_question_id),
    CONSTRAINT uk_attempt_display_order UNIQUE (attempt_id, display_order),
    CONSTRAINT fk_attempt_questions_attempt_id FOREIGN KEY (attempt_id) REFERENCES attempts (id) ON DELETE CASCADE,
    CONSTRAINT fk_attempt_questions_exam_question_id FOREIGN KEY (exam_question_id) REFERENCES exam_questions (id) ON DELETE RESTRICT
);
CREATE INDEX idx_attempt_questions_attempt_id ON attempt_questions (attempt_id);

-- [Attempt & Grading] Autosave câu trả lời từng câu.
CREATE TABLE attempt_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    attempt_question_id BIGINT NOT NULL,
    answer_payload JSONB,
    answer_text TEXT,
    sequence_number BIGINT NOT NULL DEFAULT 0,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_final BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_attempt_answer_question UNIQUE (attempt_id, attempt_question_id),
    CONSTRAINT fk_attempt_answers_attempt_id FOREIGN KEY (attempt_id) REFERENCES attempts (id) ON DELETE CASCADE,
    CONSTRAINT fk_attempt_answers_attempt_question_id FOREIGN KEY (attempt_question_id) REFERENCES attempt_questions (id) ON DELETE CASCADE
);
CREATE INDEX idx_attempt_answers_attempt_id ON attempt_answers (attempt_id);

-- [Attempt & Grading] Kết quả chấm chính thức.
CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    attempt_id BIGINT NOT NULL UNIQUE,
    automatic_score NUMERIC(10,2) NOT NULL,
    final_score NUMERIC(10,2) NOT NULL,
    max_score NUMERIC(10,2) NOT NULL,
    percentage NUMERIC(7,4),
    status VARCHAR(30) NOT NULL DEFAULT 'GRADED',
    graded_at TIMESTAMPTZ NOT NULL,
    released_at TIMESTAMPTZ,
    graded_by BIGINT,
    CONSTRAINT ck_grades_1 CHECK (automatic_score >= 0),
    CONSTRAINT ck_grades_2 CHECK (final_score >= 0),
    CONSTRAINT ck_grades_3 CHECK (max_score >= 0),
    CONSTRAINT ck_grades_4 CHECK (percentage IS NULL OR (percentage >= 0 AND percentage <= 100)),
    CONSTRAINT ck_grades_5 CHECK (status IN ('PENDING','AUTO_GRADED','NEEDS_MANUAL_GRADING','GRADED','RELEASED')),
    CONSTRAINT fk_grades_attempt_id FOREIGN KEY (attempt_id) REFERENCES attempts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_grades_graded_by FOREIGN KEY (graded_by) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_grades_status ON grades (status);

-- [Attempt & Grading] Điểm theo câu hỏi.
CREATE TABLE grade_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    grade_id BIGINT NOT NULL,
    exam_question_id BIGINT NOT NULL,
    awarded_points NUMERIC(10,2) NOT NULL,
    max_points NUMERIC(10,2) NOT NULL,
    is_correct BOOLEAN,
    grading_details JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uk_grade_item_question UNIQUE (grade_id, exam_question_id),
    CONSTRAINT fk_grade_items_grade_id FOREIGN KEY (grade_id) REFERENCES grades (id) ON DELETE CASCADE,
    CONSTRAINT fk_grade_items_exam_question_id FOREIGN KEY (exam_question_id) REFERENCES exam_questions (id) ON DELETE RESTRICT
);
CREATE INDEX idx_grade_items_grade_id ON grade_items (grade_id);

-- [Attempt & Grading] Lưu kết quả command để retry an toàn.
CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    operation VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(128),
    response_status INTEGER NOT NULL,
    response_body JSONB,
    expires_at TIMESTAMPTZ,
    CONSTRAINT uk_idempotency_user_operation_key UNIQUE (user_id, operation, idempotency_key),
    CONSTRAINT fk_idempotency_records_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX idx_idempotency_records_expires_at ON idempotency_records (expires_at);

-- Seed five system roles
INSERT INTO roles (code, name, description, system_role) VALUES
    ('SYSTEM_ADMIN', 'System Administrator', 'Quản trị nền tảng; không mặc định sở hữu dữ liệu học thuật.', TRUE),
    ('ACADEMIC_ADMIN', 'Academic Administrator', 'Quản lý cấu trúc học thuật trong phạm vi trường.', TRUE),
    ('TEACHER', 'Teacher', 'Quản lý câu hỏi, đề và ca thi trong phạm vi được giao.', TRUE),
    ('PROCTOR', 'Proctor', 'Giám sát ca thi được phân công.', TRUE),
    ('STUDENT', 'Student', 'Tham gia lớp, làm bài và xem kết quả của mình.', TRUE)
ON CONFLICT (code) DO NOTHING;

-- Seed core permissions
INSERT INTO permissions (code, name, module, description) VALUES
    ('USER_READ_SELF', 'Read own profile', 'IDENTITY', NULL),
    ('USER_UPDATE_SELF', 'Update own profile', 'IDENTITY', NULL),
    ('USER_MANAGE', 'Manage users', 'IDENTITY', NULL),
    ('ROLE_ASSIGN', 'Assign roles', 'IDENTITY', NULL),
    ('SCHOOL_READ', 'Read school data', 'ACADEMIC', NULL),
    ('SCHOOL_MANAGE', 'Manage school data', 'ACADEMIC', NULL),
    ('ACADEMIC_READ', 'Read academic data', 'ACADEMIC', NULL),
    ('ACADEMIC_MANAGE', 'Manage academic data', 'ACADEMIC', NULL),
    ('QUESTION_BANK_READ', 'Read question banks', 'QUESTION_BANK', NULL),
    ('QUESTION_BANK_CREATE', 'Create question banks', 'QUESTION_BANK', NULL),
    ('QUESTION_BANK_UPDATE', 'Update authorized question banks', 'QUESTION_BANK', NULL),
    ('QUESTION_BANK_DELETE', 'Archive authorized question banks', 'QUESTION_BANK', NULL),
    ('EXAM_READ', 'Read exams', 'EXAM', NULL),
    ('EXAM_CREATE', 'Create exams', 'EXAM', NULL),
    ('EXAM_UPDATE', 'Update authorized draft exams', 'EXAM', NULL),
    ('EXAM_PUBLISH', 'Publish authorized exams', 'EXAM', NULL),
    ('EXAM_SESSION_MANAGE', 'Manage exam sessions', 'EXAM', NULL),
    ('EXAM_SESSION_PROCTOR', 'Proctor assigned exam sessions', 'EXAM', NULL),
    ('ATTEMPT_START', 'Start eligible attempt', 'ATTEMPT', NULL),
    ('ATTEMPT_SAVE', 'Autosave own attempt', 'ATTEMPT', NULL),
    ('ATTEMPT_SUBMIT', 'Submit own attempt', 'ATTEMPT', NULL),
    ('GRADE_READ_SELF', 'Read own grades', 'GRADING', NULL),
    ('GRADE_READ_ANY', 'Read grades in authorized scope', 'GRADING', NULL),
    ('GRADE_MANAGE', 'Grade or adjust authorized attempts', 'GRADING', NULL)
ON CONFLICT (code) DO NOTHING;

-- Seed conservative role-permission mappings
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.code = 'SYSTEM_ADMIN' AND p.code IN ('USER_READ_SELF', 'USER_UPDATE_SELF', 'USER_MANAGE', 'ROLE_ASSIGN', 'SCHOOL_READ', 'SCHOOL_MANAGE', 'ACADEMIC_READ', 'ACADEMIC_MANAGE', 'QUESTION_BANK_READ', 'QUESTION_BANK_CREATE', 'QUESTION_BANK_UPDATE', 'QUESTION_BANK_DELETE', 'EXAM_READ', 'EXAM_CREATE', 'EXAM_UPDATE', 'EXAM_PUBLISH', 'EXAM_SESSION_MANAGE', 'EXAM_SESSION_PROCTOR', 'ATTEMPT_START', 'ATTEMPT_SAVE', 'ATTEMPT_SUBMIT', 'GRADE_READ_SELF', 'GRADE_READ_ANY', 'GRADE_MANAGE')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ACADEMIC_ADMIN' AND p.code IN ('USER_READ_SELF', 'USER_UPDATE_SELF', 'SCHOOL_READ', 'SCHOOL_MANAGE', 'ACADEMIC_READ', 'ACADEMIC_MANAGE', 'QUESTION_BANK_READ', 'EXAM_READ', 'GRADE_READ_ANY')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.code = 'TEACHER' AND p.code IN ('USER_READ_SELF', 'USER_UPDATE_SELF', 'SCHOOL_READ', 'ACADEMIC_READ', 'QUESTION_BANK_READ', 'QUESTION_BANK_CREATE', 'QUESTION_BANK_UPDATE', 'QUESTION_BANK_DELETE', 'EXAM_READ', 'EXAM_CREATE', 'EXAM_UPDATE', 'EXAM_PUBLISH', 'EXAM_SESSION_MANAGE', 'GRADE_READ_ANY', 'GRADE_MANAGE')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.code = 'PROCTOR' AND p.code IN ('USER_READ_SELF', 'USER_UPDATE_SELF', 'ACADEMIC_READ', 'EXAM_READ', 'EXAM_SESSION_PROCTOR')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.code = 'STUDENT' AND p.code IN ('USER_READ_SELF', 'USER_UPDATE_SELF', 'ACADEMIC_READ', 'EXAM_READ', 'ATTEMPT_START', 'ATTEMPT_SAVE', 'ATTEMPT_SUBMIT', 'GRADE_READ_SELF')
ON CONFLICT DO NOTHING;

COMMIT;
